---
name: Build
on:
  push:
    branches: [it_works_on_my_machine]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install build deps
      run: |
        sudo apt-get update
        sudo apt-get --no-install-recommends --assume-yes install debhelper dkms
    - name: build
      run: ./build.sh
    - name: upload .changes
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.CHANGES }}"
        path: "${{ env.CHANGES }}"
    - name: upload .deb
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.DEB }}"
        path: "${{ env.DEB }}"
